// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Meso.DAL.Certificaciones.Entities;

[Index("FacturaId", Name = "IX_Detalle_Factura")]
public partial class DTE_Detalle
{
    [Key]
    public int DetalleId { get; set; }

    [Required]
    [StringLength(200)]
    public string Nombre { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Precio { get; set; }

    public int Cantidad { get; set; }

    public int FacturaId { get; set; }

    [ForeignKey("FacturaId")]
    [InverseProperty("DTE_Detalle")]
    public virtual DTE_Factura Factura { get; set; }
}