// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Meso.DAL.Certificaciones.Entities;

[Index("Estado", Name = "IX_Factura_Estado")]
[Index("FechaEmision", Name = "IX_Factura_Fecha")]
public partial class DTE_Factura
{
    [Key]
    public int FacturaId { get; set; }

    public DateTime FechaEmision { get; set; }

    public DateTime FechaIngreso { get; set; }

    [Required]
    [StringLength(35)]
    public string ClienteNIT { get; set; }

    [Required]
    [StringLength(300)]
    public string ClienteRazonSocial { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Total { get; set; }

    public byte Estado { get; set; }

    public DateTime? FechaProcesamiento { get; set; }

    public int EstablecimientoId { get; set; }

    [InverseProperty("Factura")]
    public virtual DTE_Anulacion DTE_Anulacion { get; set; }

    [InverseProperty("Factura")]
    public virtual DTE_Certificacion DTE_Certificacion { get; set; }

    [InverseProperty("Factura")]
    public virtual ICollection<DTE_Detalle> DTE_Detalle { get; set; } = new List<DTE_Detalle>();

    [ForeignKey("EstablecimientoId")]
    [InverseProperty("DTE_Factura")]
    public virtual Establecimiento Establecimiento { get; set; }

    [InverseProperty("Factura")]
    public virtual ICollection<Logs_Bitacora> Logs_Bitacora { get; set; } = new List<Logs_Bitacora>();
}