// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Meso.DAL.Certificaciones.Entities;

[Index("FacturaId", Name = "UQ__DTE_Anul__5C024864021D9756", IsUnique = true)]
public partial class DTE_Anulacion
{
    [Key]
    public int AnulacionId { get; set; }

    [Required]
    [StringLength(500)]
    public string Motivo { get; set; }

    public DateTime FechaIngreso { get; set; }

    public DateTime FechaAnulacion { get; set; }

    public DateTime? FechaProcesamiento { get; set; }

    public int FacturaId { get; set; }

    [ForeignKey("FacturaId")]
    [InverseProperty("DTE_Anulacion")]
    public virtual DTE_Factura Factura { get; set; }
}