// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Meso.DAL.Certificaciones.Entities;

[Index("FacturaId", Name = "UQ__DTE_Cert__5C02486472A416D5", IsUnique = true)]
public partial class DTE_Certificacion
{
    [Key]
    public int CertificacionId { get; set; }

    [Required]
    [StringLength(50)]
    public string NumeroAutorizacion { get; set; }

    [Required]
    [StringLength(50)]
    public string Serie { get; set; }

    public int Correlativo { get; set; }

    public DateTime FechaIngreso { get; set; }

    public DateTime? FechaProcesamiento { get; set; }

    public DateTime FechaCertificacion { get; set; }

    public int FacturaId { get; set; }

    [ForeignKey("FacturaId")]
    [InverseProperty("DTE_Certificacion")]
    public virtual DTE_Factura Factura { get; set; }
}