// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Meso.DAL.Certificaciones.Entities;

[Index("Nit", Name = "UQ__Emisor__C7D1D6DA07F78DCA", IsUnique = true)]
public partial class Emisor
{
    [Key]
    public int EmisorId { get; set; }

    [Required]
    [StringLength(12)]
    public string Nit { get; set; }

    [Required]
    [StringLength(200)]
    public string RazonSocial { get; set; }

    public bool EstadoActivo { get; set; }

    public bool PuedeCertificar { get; set; }

    public DateTime FechaRegistro { get; set; }

    [InverseProperty("Emisor")]
    public virtual ICollection<Establecimiento> Establecimiento { get; set; } = new List<Establecimiento>();
}