// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Meso.DAL.Certificaciones.Entities;

public partial class Establecimiento
{
    [Key]
    public int EstablecimientoId { get; set; }

    [Required]
    [StringLength(200)]
    public string NombreEstablecimiento { get; set; }

    [Required]
    [StringLength(35)]
    public string NIT { get; set; }

    [Required]
    [StringLength(300)]
    public string Direccion { get; set; }

    public bool EstadoActivo { get; set; }

    [Required]
    [StringLength(12)]
    public string CodigoUnicoEstablecimiento { get; set; }

    public int EmisorId { get; set; }

    [InverseProperty("Establecimiento")]
    public virtual ICollection<DTE_Factura> DTE_Factura { get; set; } = new List<DTE_Factura>();

    [ForeignKey("EmisorId")]
    [InverseProperty("Establecimiento")]
    public virtual Emisor Emisor { get; set; }
}