// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Meso.DAL.Certificaciones.Entities;

public partial class Logs_Bitacora
{
    [Key]
    public int BitacoraId { get; set; }

    [Required]
    [StringLength(50)]
    public string Accion { get; set; }

    public DateTime FechaAccion { get; set; }

    [Required]
    [StringLength(1000)]
    public string Descripcion { get; set; }

    public DateTime? FechaProcesamiento { get; set; }

    public int FacturaId { get; set; }

    [ForeignKey("FacturaId")]
    [InverseProperty("Logs_Bitacora")]
    public virtual DTE_Factura Factura { get; set; }
}